# Generated by Django 4.2.1 on 2023-06-22 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='observacoes',
            field=models.TextField(null=True, verbose_name='Observações'),
        ),
    ]
