# Generated by Django 4.2.1 on 2023-06-27 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0002_reserva_observacoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='observacoes',
            field=models.TextField(help_text='Digite aqui', null=True, verbose_name='Observações'),
        ),
    ]
