# Generated by Django 4.2.1 on 2023-07-13 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0007_alter_reserva_petshop'),
    ]

    operations = [
        migrations.CreateModel(
            name='EspeciesPet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especie', models.CharField(max_length=50, verbose_name='Espécie')),
            ],
        ),
    ]
