# Generated by Django 4.2.1 on 2023-07-13 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0012_alter_reserva_especie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='especie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='RACA', to='reserva.especiespet'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reserva',
            name='petshop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='reserva.petshop'),
            preserve_default=False,
        ),
    ]
