# Generated by Django 4.2.1 on 2023-07-13 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0013_alter_reserva_especie_alter_reserva_petshop'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='especiespet',
            options={'verbose_name': 'Especie', 'verbose_name_plural': 'Especies'},
        ),
        migrations.AlterModelOptions(
            name='petshop',
            options={'verbose_name': 'Petshop', 'verbose_name_plural': 'Petshops'},
        ),
    ]
